/*
 * Copyright 2010-2022 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.code.coloring.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("plugins/code-coloring/testData/callGraph")
@TestDataPath("$PROJECT_ROOT")
public class CallGraphTestGenerated extends AbstractCallGraphTest {
    @Test
    @TestMetadata("abstract_method.kt")
    public void testAbstract_method() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/abstract_method.kt");
    }

    @Test
    public void testAllFilesPresentInCallGraph() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("plugins/code-coloring/testData/callGraph"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("class_ctor.kt")
    public void testClass_ctor() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/class_ctor.kt");
    }

    @Test
    @TestMetadata("class_method.kt")
    public void testClass_method() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/class_method.kt");
    }

    @Test
    @TestMetadata("indirect_recursion.kt")
    public void testIndirect_recursion() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/indirect_recursion.kt");
    }

    @Test
    @TestMetadata("multiple_packages.kt")
    public void testMultiple_packages() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/multiple_packages.kt");
    }

    @Test
    @TestMetadata("overrides.kt")
    public void testOverrides() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/overrides.kt");
    }

    @Test
    @TestMetadata("proto.kt")
    public void testProto() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/proto.kt");
    }

    @Test
    @TestMetadata("simple.kt")
    public void testSimple() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/simple.kt");
    }

    @Test
    @TestMetadata("unit_test.kt")
    public void testUnit_test() throws Exception {
        runTest("plugins/code-coloring/testData/callGraph/unit_test.kt");
    }
}
